### ISSUE TITLE
There is an incredibly amount of verbose output when a buildpack is not matched

### ISSUE THREAD

**Issue by n0n0x** [teamhephy/workflow#109] opened 2019-12-28 20:15 UTC
As it can be seen in the following image, when not setting a specific buildpack via [`BUILDPACK_URL`](https://docs.teamhephy.com/applications/using-buildpacks/#using-a-custom-buildpack), the slugbuilder cycles through every installed buildpack until it detects the actual programming language ([code for reference](https://github.com/teamhephy/slugbuilder/blob/2f0976d87b2ce698458a6dbe9f04d0139d7a1381/rootfs/builder/build.sh#L158-L162)): 

![image](https://user-images.githubusercontent.com/800750/71548889-8c5c1e00-2993-11ea-8633-d3dafc8e3b18.png)

This is great, but in the past year, buildpacks like [nodejs](https://github.com/heroku/heroku-buildpack-nodejs/commit/545b330ba3455b5b790f69f1337e93d9fbbb1e44) and [php](https://github.com/heroku/heroku-buildpack-php/commit/e24f04077472ad5583afa7c59c66430bcf8644a3) have increased their verbosity when the app is not detected. Leading to something like the following output when deploying using deis:

<img width="554" alt="Screen Shot 2019-11-25 at 09 28 50" src="https://user-images.githubusercontent.com/800750/71548830-c24cd280-2992-11ea-844f-78c9f174ca09.png">

I would like to change this behavior by setting a variable like `DEIS_BUILDPACK_DEBUG` to `True` or `False` (defaulting to `False` and suppressing such output). This way the output would look cleaner as following:

![image](https://user-images.githubusercontent.com/800750/71549035-8404e280-2995-11ea-8f58-2f3e587eced9.png)

**Comment by Cryptophobia** [comment] 2020-01-01 19:20
Very good improvement @n0n0x . Have you tested this with the builder and slugbuilder changes?

**Comment by n0n0x** [comment] 2020-01-01 22:13
Hello!! Thanks!

Regarding documentation, this would be more of a per-app setting. So I think I should document this setting here: https://github.com/teamhephy/workflow/blob/master/src/applications/deploying-apps.md#tuning-application-settings

what do you think?

About testing: We are using this branch in production right now :) But we are mainly python focused. So if anyone can try this using any other programming language, it would be great! The images that we are using are:

* slugrunner: `n0n0x/slugrunner:less-verbose-buildpacks`
* builder: `n0n0x/builder:less-verbose-buildpacks`

Here are some screenshots:

### Without `DEIS_BUILDPACK_DEBUG` set
![image](https://user-images.githubusercontent.com/800750/71646485-28559480-2cc8-11ea-8086-d03d3bd808c0.png)

### With `DEIS_BUILDPACK_DEBUG=True`
![image](https://user-images.githubusercontent.com/800750/71646500-6fdc2080-2cc8-11ea-9ef1-96a48749c003.png)

### With `DEIS_BUILDPACK_DEBUG=False`
![image](https://user-images.githubusercontent.com/800750/71646530-d2cdb780-2cc8-11ea-9d7a-4fd7731a6c29.png)

**Comment by Cryptophobia** [comment] 2020-01-01 22:31
> Regarding documentation, this would be more of a per-app setting. So I think I should document this setting here: https://github.com/teamhephy/workflow/blob/master/src/applications/deploying-apps.md#tuning-application-settings

> what do you think?

Yes, you are right @n0n0x. Good catch! This should be documented and set per app similar to `BUILDPACK_URL`. Actually looks like environment variable `BUILDPACK_URL` is missing from the above documentation, so if you can put it in there as well while working on this, that would be great. :)

Thank you for the examples. I can go ahead and test a bit with your images as well. I will test with some rails and golang apps and the https://github.com/teamhephy/example-rails5-reactjs example app. Anything that limits noise during the slugbuilding process would be nice since this verbose output is pretty useless.

Since the above change is pretty isolated via a flag, we don't have to worry about it as much unless there is some kind of regression.

**Comment by n0n0x** [comment] 2020-01-01 22:56
@Cryptophobia done with documentation in #111!

**Comment by Cryptophobia** [comment] 2020-01-02 00:04
closed by https://github.com/teamhephy/workflow/pull/111, https://github.com/teamhephy/builder/pull/54, and https://github.com/teamhephy/slugbuilder/pull/16

**Closed** 2020-01-02 00:04 UTC
