### ISSUE TITLE
deis logs is not returning pod logs

### ISSUE THREAD

**Issue by dmcnaught** [teamhephy/workflow#135] opened 2020-10-20 16:19 UTC
I’m getting no output from deis logs in my test cluster: 
K8s 1.18.10
workflow 2.22.1
cluster on aws created with kops 1.18.1
instance image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
```» kubectl -n test get po
NAME                        READY   STATUS    RESTARTS   AGE
test-cmd-69d5bf78b8-nfcs9   1/1     Running   0          42h
test-cmd-69d5bf78b8-zxxw5   1/1     Running   0          42h
--- kubernetes/deis ‹master* M?› » kubectl -n test logs test-cmd-69d5bf78b8-nfcs9                                                                                                              1 ↵
100.96.4.26 - - [19/Oct/2020:15:25:00 +0000] "GET / HTTP/1.1" 200 685 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36"
--- kubernetes/deis ‹master* M?› » kubectl -n test logs test-cmd-69d5bf78b8-zxxw5
100.96.4.26 - - [19/Oct/2020:15:25:00 +0000] "GET /favicon.ico HTTP/1.1" 200 685 "<URL>" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36"
--- kubernetes/deis ‹master* M?› » deis logs -a test
Error: There are currently no log messages. Please check the following things:
1) Logger and fluentd pods are running: kubectl --namespace=deis get pods.
2) The application is writing logs to the logger component by checking that an entry in the ring buffer was created: kubectl --namespace=deis logs <logger pod>
3) Making sure that the container logs were mounted properly into the fluentd pod: kubectl --namespace=deis exec <fluentd pod> ls /var/log/containers
3a) If the above command returns saying /var/log/containers cannot be found then please see the following github issue for a workaround: https://github.com/deis/logger/issues/50
--- kubernetes/deis ‹master* M?› »
```

**Comment by Cryptophobia** [comment] 2020-10-20 16:41
This is a weird issue because it works on my cluster. Created using the same versions of kops and running the same version of workflow.

@dmcnaught , what happens when you type the command above into the fluentd pod:

```bash
kubectl --namespace=deis exec <fluentd pod> ls /var/log/containers
```

**Comment by dmcnaught** [comment] 2020-10-20 23:17
Here is the output
```
» ku -n deis exec deis-logger-fluentd-hqf2n ls /var/log/containers
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
alb-ingress-controller-85b5fc7cdf-24ws2_kube-system_alb-ingress-controller-50eee6f4dda74208cf98eb26ac83ce499a9473a19ff9b4af9ac03e9007ecd71b.log
alertmanager-main-0_monitoring_alertmanager-6dd370aff6390e62fb8bda7c618e9bd07bd7ebba56dc2dd4f5d3e05202a4b23a.log
alertmanager-main-0_monitoring_config-reloader-3fe7a568275b9ae330d91b265f36da0fbc08224965341289a80b82870bd961ed.log
alertmanager-main-1_monitoring_alertmanager-096110e98fb561f7e461e93c08229ee7367aafc150333cc89848211568f8820d.log
alertmanager-main-1_monitoring_config-reloader-1fd9223f2fd1098085ac54f9e4529e09e40742dee862ae54042f30abe581d8d2.log
alertmanager-main-2_monitoring_alertmanager-12618dbbe88e78e4625b48d5fbf69c4575a30d7bbc97b9467b17798dae3aa48b.log
alertmanager-main-2_monitoring_config-reloader-a1e3f7f3cccb5aeb4cbc00d7c57d3ca6c9ce57e2a68a922d602b60d9edea4861.log
deis-controller-fd5758fc8-nm9tv_deis_deis-controller-070bb25b8b21ed759d1323dd3cf3059ddce940d86244a65ae2e23e9f3a9cdb53.log
deis-controller-fd5758fc8-nm9tv_deis_deis-controller-e5b5b1856827022b6d38925ef951b526e92d5e6045a7278610290ff492e9a090.log
deis-logger-6fd77f84f7-bvr9r_deis_deis-logger-c373b67f2059554ea876a066fc19e30135d7ceef8dab30fefa6e0fb605466452.log
deis-logger-fluentd-hqf2n_deis_deis-logger-fluentd-ded25a807270801ec17127026950eb4936fe7afdfa66e0e0ea74a5e1c3137b73.log
deis-logger-redis-778d97656d-wdzwj_deis_deis-logger-redis-e941b5d32338d6f95a5b6b82ccea1e0e92c4f2788efbd5822f81db9c83f9fb11.log
deis-monitor-grafana-d9d689dbd-6b4wg_deis_deis-monitor-grafana-d1312e6625940583f4b368ea52828c04f34b26aecc47c9a0c1ad7a97b604eb44.log
deis-monitor-influxdb-54649ff4c6-2klqh_deis_deis-monitor-influxdb-4e4159f350dec72085e287fac712b979fcf45c6a3d3c63c81953c9f22d692e2f.log
deis-monitor-telegraf-fxgx6_deis_deis-monitor-telegraf-f3e290a1e86d8ce87bc4b3a5574d4a5faeb5e4fd1a4e9b6b3e201fa7e85a9056.log
deis-nsqd-57b4d9cd57-m6h4j_deis_deis-nsqd-161b964789397ec5fefb792ced5870e2cd33eeb1637a2e1f3fe8ea77fabb88cb.log
deis-nsqd-57b4d9cd57-tv27r_deis_deis-nsqd-4bb0bd6cd91957a2f10364dc8fe040775df52c32c90415b3a7b0140e6b00e7a7.log
deis-router-75b6d59d6-b4pdj_deis_deis-router-3fab038f63f26199830ded4ab989338ea328b874bea0ec648a041b0b9535c399.log
deis-router-75b6d59d6-gjv5g_deis_deis-router-7842c56fddf704ca0aeafd15b782dd93d6c4445a637fc2ad6a148dd6938e7ff5.log
deis-workflow-manager-98c654754-85xdr_deis_deis-workflow-manager-df181ee689cbdc34a0adc8e391d88ca3f7c468246fb8b987627c3891a54451d6.log
efs-csi-node-dztg9_kube-system_csi-driver-registrar-6e80a04ce559d1a0b0f56608ba52ee9be3825d25156302eddac7a5c447080b91.log
efs-csi-node-dztg9_kube-system_efs-plugin-c74df6a07b01683498e5465415da0c4beee8e35513902c9b060f9c3af86f792d.log
efs-csi-node-dztg9_kube-system_liveness-probe-a0a3f8404d6c4848369335fffdfbceb398fe4c22cfc92f76d5b3ab1a37bceb4c.log
grafana-7cb8c9bdfd-jwh9r_monitoring_grafana-0a9900a6d21053e7a50283ade12c5a7e29bb28fb92e42e9387c204a69bc68b32.log
kube-dns-6c699b5445-fvxs5_kube-system_dnsmasq-d39788aba2cca87016301fe67028538e95c27ecaade078ef0bf648674019f40c.log
kube-dns-6c699b5445-fvxs5_kube-system_kubedns-ed6221d55596e647e7d179dbf43737225196db484e4fe483e248df31c3aecb23.log
kube-dns-6c699b5445-fvxs5_kube-system_sidecar-f889003700c83ce4c2343472f7e7ab2a4e48151772e050e7e775088c0eb416dc.log
kube-dns-6c699b5445-m69bq_kube-system_dnsmasq-1c9fbf79d4026b821b0edd874d0fc65becff9fbefa270071fa8073b5050f9b92.log
kube-dns-6c699b5445-m69bq_kube-system_kubedns-5a6ccb68673e254a94af5545dcbafc48c63d5c11831c41dd62d187d06ff70a1c.log
kube-dns-6c699b5445-m69bq_kube-system_sidecar-bd16d834da34ef0526d83bcc2b671099a746cb7670e5926747478fc113ef3f12.log
kube-dns-autoscaler-cd7778b7b-29m8w_kube-system_autoscaler-1286f771e4cc92cdc3e1f72e0220c24ca75eba4515859f5c72ee259116bc7825.log
kube-proxy-ip-10-53-133-90.ec2.internal_kube-system_kube-proxy-49c17da3e5fa711b311005384e3c0539c3fa3290739049bc3eeb96701f8cfa53.log
kube-state-metrics-bdb8874fd-rtr66_monitoring_kube-rbac-proxy-main-befaea729adc350c203d64f8e9d3be095fb1625623857a96ba01999af6a77294.log
kube-state-metrics-bdb8874fd-rtr66_monitoring_kube-rbac-proxy-self-9c4947d1727921e35a1dd0468d1a6c59858c32125759a08fee5fc5397d25b92a.log
kube-state-metrics-bdb8874fd-rtr66_monitoring_kube-state-metrics-ce5a93ac83774d31147d7808afe70c5cce348cb0287e1549db5f6a0ccc9e88d7.log
metrics-server-659cc5f668-t7vwn_kube-system_metrics-server-e677ca562ef54a6d18ebf20bb324734c208416850cddf91171411042fd23e43c.log
newrelic-infra-v6n9p_default_newrelic-infra-8214049f1aeaeda86b4c65d871f18b7ebaabd48a79df899e7c71fc31f69c6516.log
newrelic-infra-v6n9p_default_newrelic-infra-f3a9367c115a94d2e21aaa0b53ef4557401a0e2f983e64b8af0713775b0101c1.log
node-exporter-nb6vq_monitoring_kube-rbac-proxy-cf55ba4a32a7a648d62da202e08960e5a13d54dca34a4a0c4f8eddb31b1a7664.log
node-exporter-nb6vq_monitoring_node-exporter-7e8907aa7d14f2c62070511cdc27891c6d4cd8feaf7d40b3a8e5c3316a8df5e2.log
prometheus-k8s-0_monitoring_prometheus-93f960edc9ffaeda03cf6f1a44123061dae1199584f4723b62cc399b078506f0.log
prometheus-k8s-0_monitoring_prometheus-bd9f2fb7908706c42ffd93438b4cec84a1bf6a2ff5b288b9d2b4ab30c43e08ba.log
prometheus-k8s-0_monitoring_prometheus-config-reloader-0f5f201777ab345a3fe675da67885a417cfa715e65ba457cb82275a2301fea08.log
prometheus-k8s-0_monitoring_rules-configmap-reloader-333201f184b57ccd74281d90346f62c38f09286821c7fe7bd47e9c4dfc9d3e34.log
prometheus-k8s-1_monitoring_prometheus-1d2abe1835227cd7916c5c1809adf2df63c1618c143cbfbf016a854d03759d0b.log
prometheus-k8s-1_monitoring_prometheus-30cec6ea9703b4970d2972f4d9b00a762a24035c69b60bf5714fbb9b3f26538b.log
prometheus-k8s-1_monitoring_prometheus-config-reloader-6f2b56885c4698d5a93a75e195eb166861311a0ded6918c2de288225a584054f.log
prometheus-k8s-1_monitoring_rules-configmap-reloader-273968a813da0d63a44c83acbdaa0aea6017cd70feaa53a7f8fd69ded71d82fa.log
prometheus-operator-7b598df7f7-fp662_monitoring_kube-rbac-proxy-0db95c5a9ac33337878610658db98c75cbd8065af430c85afd43620de36ef597.log
prometheus-operator-7b598df7f7-fp662_monitoring_prometheus-operator-9a9bdf1491fe00293b3f75830cc325552847d326b1d0b2cc46323ef31439b9e9.log
splunk-connect-splunk-kubernetes-logging-5j28q_default_splunk-fluentd-k8s-logs-90d2769c07cb20cde6e548d79acc034eb10af124a228edf90629aa3e14c9ae11.log
splunk-connect-splunk-kubernetes-metrics-4f845_default_splunk-fluentd-k8s-metrics-18923fd46c7c07d33ca011bf44f38dfbab93ab7cf84ec486b99a15db9f4aae79.log
splunk-connect-splunk-kubernetes-metrics-agg-595d45c878-hlwvv_default_splunk-fluentd-k8s-metrics-agg-cce43cc3a26a006bb59fba008c3eabaa9562a7b72505e645be6e8f682fa647b7.log
splunk-connect-splunk-kubernetes-objects-58bf66f44d-kkzcx_default_splunk-fluentd-k8s-objects-132140367feb7c90cae01965530ff55d4a0bcf738232bc6d6d135facf4db78b0.log
test-alb-95ff476f7-2vwbs_test-alb_test-alb-916aff74072390c9d4fb525fb7bfeeee1a88844c1a66c70f8865b047e6e41450.log
test-cmd-69d5bf78b8-nfcs9_test_test-cmd-f89d2880ca7adaf92a476c7b60d7d77140643f83374b25261f15bd2243052d65.log
test-cmd-69d5bf78b8-zxxw5_test_test-cmd-b49a6adbc4ed1f3fb26aa92a2e4f0e10d1d279880df02c6af16fa91290bed59b.log
test2-cmd-d8dd4ff9c-zqwh9_test2_test2-cmd-ccec8e0bed344699a760f1eca88b72f12664398a89d5b1adea9306476790808a.log
```

and yes, you can see the output of kubectl pasted in the original ticket. I hit the pod a few more times and tried again:

```
» ku -n test get po                                                                                                                         1 ↵
NAME                        READY   STATUS    RESTARTS   AGE
test-cmd-69d5bf78b8-nfcs9   1/1     Running   0          2d1h
test-cmd-69d5bf78b8-zxxw5   1/1     Running   0          2d1h
--- kubernetes/kops ‹master* M?› » ku -n test
--- kubernetes/kops ‹master* M?› » deis logs -a test                                                                                                                       130 ↵
Error: There are currently no log messages. Please check the following things:
1) Logger and fluentd pods are running: kubectl --namespace=deis get pods.
2) The application is writing logs to the logger component by checking that an entry in the ring buffer was created: kubectl --namespace=deis logs <logger pod>
3) Making sure that the container logs were mounted properly into the fluentd pod: kubectl --namespace=deis exec <fluentd pod> ls /var/log/containers
3a) If the above command returns saying /var/log/containers cannot be found then please see the following github issue for a workaround: https://github.com/deis/logger/issues/50
--- kubernetes/kops ‹master* M?› » ku -n test logs test-cmd-69d5bf78b8-nfcs9                                                                                                 1 ↵
100.96.4.26 - - [19/Oct/2020:15:25:00 +0000] "GET / HTTP/1.1" 200 685 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36"
100.96.4.26 - - [20/Oct/2020:23:14:01 +0000] "GET /favicon.ico HTTP/1.1" 200 685 "URL" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36"
100.96.4.26 - - [20/Oct/2020:23:14:03 +0000] "GET / HTTP/1.1" 200 685 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36"
100.96.4.26 - - [20/Oct/2020:23:14:04 +0000] "GET /favicon.ico HTTP/1.1" 200 685 "URL" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36"
100.96.4.26 - - [20/Oct/2020:23:14:04 +0000] "GET / HTTP/1.1" 200 685 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36"
--- kubernetes/kops ‹master* M?› » ku -n test logs test-cmd-69d5bf78b8-zxxw5
100.96.4.26 - - [19/Oct/2020:15:25:00 +0000] "GET /favicon.ico HTTP/1.1" 200 685 "URL" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36"
100.96.4.26 - - [20/Oct/2020:23:14:00 +0000] "GET / HTTP/1.1" 200 685 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36"
100.96.4.26 - - [20/Oct/2020:23:14:05 +0000] "GET /favicon.ico HTTP/1.1" 200 685 "URL" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36"
--- kubernetes/kops ‹master* M?› » deis logs -a test
Error: There are currently no log messages. Please check the following things:
1) Logger and fluentd pods are running: kubectl --namespace=deis get pods.
2) The application is writing logs to the logger component by checking that an entry in the ring buffer was created: kubectl --namespace=deis logs <logger pod>
3) Making sure that the container logs were mounted properly into the fluentd pod: kubectl --namespace=deis exec <fluentd pod> ls /var/log/containers
3a) If the above command returns saying /var/log/containers cannot be found then please see the following github issue for a workaround: https://github.com/deis/logger/issues/50
--- kubernetes/kops ‹master* M?› »
```

**Comment by dmcnaught** [comment] 2020-10-21 17:06
I just tested in my 2nd test cluster, and it is also showing the problem
One cluster is kops private topology, and the other is public topology...

**Comment by kingdonb** [comment] 2020-11-03 18:01
This is still on my radar and top of mind to fix, although I haven't been able to document the reproduce steps yet. (I believe there are some clusters which have not had this problem.)

**Comment by Cryptophobia** [comment] 2020-11-08 01:19
:+1:  @dmcnaught , I haven't tested but https://github.com/teamhephy/fluentd/pull/17 will fix this issue. I found particular commit that is a mistake. Fluent.conf being misspelled here when using the new version of fluentd container:

https://github.com/teamhephy/fluentd/commit/b6885dd84f409212c555a28dd8f1164e64129f64

**Comment by kingdonb** [comment] 2020-11-15 04:22
https://github.com/teamhephy/fluentd/pull/17 was merged and apparently hasn't been released yet, but I am still trying to reproduce this issue for the record books. I was unable to repro the problem on DigitalOcean K8s, next testing Azure AKS:

(It worked OK on a Loft instance inside of AKS, (but that's basically running on k3s, not aks...)

**Comment by Cryptophobia** [comment] 2021-01-03 01:00
This should be fixed in the last two latest release now. Thanks for reporting @dmcnaught  :)

**Closed by Cryptophobia** 2021-01-03 01:00 UTC
