### ISSUE TITLE
Unable to install hephy workflow

### ISSUE THREAD

**Issue by ChillarAnand** [teamhephy/workflow#115] opened 2020-04-01 08:25 UTC
While following docs on setting up workflow, I ran the following command which is failing. Looks like this is deprecated and needs to replace with apps/v1?

```
➜ helm install hephy/workflow --namespace deis --set router.host_port.enabled=true
Error: validation failed: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]
```

**Comment by kingdonb** [comment] 2020-04-01 21:17
The issue is for sure deprecated `extensions/v1beta1` api, we need to add support for `apps/v1` (which is not landed in Workflow release yet.)

You're absolutely right, but for now there are two options:

1. You can install an earlier kubelet version, the deprecation was made final in 1.16.0 so you can still use the latest Workflow release, v2.21.4, with kubelet control plane 1.15.10
2. You can still enable those deprecated API groups, at least up to Kubelet 1.17.x (not sure about 1.18) by passing a runtime-config at (I think) kubelet start time:

```
--runtime-config=extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true,extensions/v1beta1/replicasets=true,extensions/v1beta1/networkpolicies=true
```

This is a priority issue for us, thanks for reporting it; I think we will keep this open even though we are already aware, and there are other issues representing this problem, because it is a blocker for new users who might not know anything about API deprecations yet, (in some near future state we'd like to hopefully be able to keep it that way at least until you know the ropes!)

**Comment by ChillarAnand** [comment] 2020-04-02 05:42
@kingdonb Thanks for the quick reply. 

I have created a new minikube cluster with v1.15.11 and when installing workflow, it fails with 
```
➜  ~ helm install hephy/workflow --namespace deis --set router.host_port.enabled=true
NAME:   pruning-orangutan
Error: transport is closing
```

**Comment by kingdonb** [comment] 2020-04-02 12:02
@ChillarAnand We discovered this the other day as well, sorry I did not include it in my reply

For some reason, Hephy Workflow also does not currently appear to work with Helm 2.16.x

Helm 2.15.x and Helm 3.x are both OK with the latest Hephy Workflow, from my testing at least. Not sure why Helm 2.16 has a problem, but it does seem to have more than one problem here, perhaps trying to warn us about problems in our chart before similar breaking changes land in Helm 3? We've also had verification that Helm 2.14.x works fine. Also found that Helm 3.1.2 seemingly works fine. We did not have to change our charts at all to accommodate the major upgrade.

We seen different issues with Helm 2.16. If you look at your kube-system tiller deployment pod's logs after `transport is closing`, you will probably see that it's crashing with something like this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14e314f]
goroutine 832 [running]:
k8s.io/helm/pkg/kube.getSelectorFromObject(0x1c01c40, 0xc00087a000, 0xc00087a000, 0x0)
	/go/src/k8s.io/helm/pkg/kube/client.go:924 +0x26f
k8s.io/helm/pkg/kube.(*Client).getSelectRelationPod(0xc00030a3a0, 0xc000238e00, 0xc000af8030, 0xc000b07770, 0x18, 0xc0000ea648)
	/go/src/k8s.io/helm/pkg/kube/client.go:1104 +0x195
k8s.io/helm/pkg/kube.(*Client).Get.func2(0xc000238e00, 0x0, 0x0)
	/go/src/k8s.io/helm/pkg/kube/client.go:366 +0xd1
k8s.io/helm/pkg/kube.batchPerform.func1(0xc00008f0e0, 0xc00079aea0, 0xc0003e0e10, 0xc000238e00)
	/go/src/k8s.io/helm/pkg/kube/client.go:752 +0x30
created by k8s.io/helm/pkg/kube.batchPerform
	/go/src/k8s.io/helm/pkg/kube/client.go:751 +0xb8
```

We saw different errors when users bumped their Helm client back down to an earlier version but forgot to `helm init --upgrade` to bring tiller version to the same mark. Make sure your Helm server and client versions match in `helm version` output if you are still on Helm 2.x.

It does not seem right to me that charts which worked fine in 2.15.x are broken in 2.16.x, but I also thought the Helm 2.x release series would be over at the end of the 2.15.x line, I will see if the Helm team can help, I can't say if there's a good explanation for this. @bacongobbler ?

It also seemed that Helm 2.16.x was pulling a much older version of Hephy Workflow from the chart museum library. Please note the latest version is v2.21.4, not v2.20.1. Maybe this is sorting differently because our chart version is not strictly semver (the `v` is not in the semver spec)?

```
$ helm ls
NAME 	REVISION	UPDATED                 	STATUS  	CHART           	APP VERSION	NAMESPACE
hephy	2       	Sat Mar 28 10:40:57 2020	DEPLOYED	workflow-v2.20.1	           	deis
```

I looked through some other current charts and they all seemed to be compliant with this strict interpretation of semver, so maybe this is something we need to change on our end. I did not find a chart maintainer guide to moving to Helm 3 but I'm sure there is such a guide, my goog-fu is the problem.  From the Helm.sh home page it looks like Helm 2.15 is not quite advertised anymore, only 2.16 and 2.14, it's not clear to me why this is either. (I'd recommend going with Helm 3, as it is the latest version and worked without issues under our supported k8s versions.)

**Comment by ChillarAnand** [comment] 2020-04-02 14:30
@kingdonb Thanks for the detailed explanation and suggesting a solution.

I upgraded helm to 3.x and it still failed to install workflow. However downgrading helm to 2.15.2 worked. It installed workflow. 

Some of the pods are in CrashLoopBackOff state.

```
➜  k8s kd get po
NAME                                     READY   STATUS              RESTARTS   AGE
deis-builder-57cf7db484-v7dp5            0/1     Running             2          67m
deis-controller-7fbd88b5f8-gdf76         1/1     Running             3          67m
deis-database-66f68b9776-ws4lr           1/1     Running             0          67m
deis-logger-58bb65fdd7-hhkjl             1/1     Running             2          67m
deis-logger-fluentd-bk8p6                0/1     CrashLoopBackOff    18         67m
deis-logger-redis-5976d6ddc7-66jqr       1/1     Running             0          67m
deis-minio-54f57f88b8-ppp5x              1/1     Running             0          67m
deis-monitor-grafana-6454b46bd8-67j6m    1/1     Running             0          67m
deis-monitor-influxdb-69f85d6d56-jv8ph   1/1     Running             0          67m
deis-monitor-telegraf-d9xqc              0/1     RunContainerError   18         67m
deis-nsqd-6dc776449-5hcrp                1/1     Running             0          67m
deis-registry-677fdfd6cf-6hgxw           1/1     Running             1          67m
deis-registry-proxy-r5x82                1/1     Running             0          67m
deis-router-f9998457c-8c4sz              0/1     CrashLoopBackOff    25         67m
deis-workflow-manager-5564f67d4-2lxb9    1/1     Running             0          67m

➜  k8s kd logs deis-router-f9998457c-8c4sz
2020/04/02 14:19:38 INFO: Starting nginx...
2020/04/02 14:19:38 INFO: nginx started.
2020/04/02 14:19:38 Error building model; not modifying certs or configuration: deployments.extensions "deis-router" is forbidden: User "system:serviceaccount:deis:deis-router" cannot get resource "deployments" in API group "extensions" in the namespace "deis".
2020/04/02 14:19:48 Error building model; not modifying certs or configuration: deployments.extensions "deis-router" is forbidden: User "system:serviceaccount:deis:deis-router" cannot get resource "deployments" in API group "extensions" in the namespace "deis".
2020/04/02 14:19:58 Error building model; not modifying certs or configuration: deployments.extensions "deis-router" is forbidden: User "system:serviceaccount:deis:deis-router" cannot get resource "deployments" in API group "extensions" in the namespace "deis".
2020/04/02 14:20:08 Error building model; not modifying certs or configuration: deployments.extensions "deis-router" is forbidden: User "system:serviceaccount:deis:deis-router" cannot get resource "deployments" in API group "extensions" in the namespace "deis".


➜  k8s kd logs deis-logger-fluentd-bk8p6 
2020-04-02 14:26:57 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluentd.conf"
#<Thread:0x00005634bf0d48d8@/usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.4/lib/fluent/plugin/filter_kubernetes_metadata.rb:243 run> terminated with exception (report_on_exception is true):
/usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.4/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:34:in `rescue in start_namespace_watch': start_namespace_watch: Exception encountered setting up namespace watch from Kubernetes API v1 endpoint https://10.96.0.1:443: namespaces is forbidden: User "system:serviceaccount:deis:deis-logger-fluentd" cannot list resource "namespaces" in API group "" at the cluster scope ({"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \"system:serviceaccount:deis:deis-logger-fluentd\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope","reason":"Forbidden","details":{"kind":"namespaces"},"code":403} (Fluent::ConfigError)
)
        from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.4/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:27:in `start_namespace_watch'
        from /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.4/lib/fluent/plugin/filter_kubernetes_metadata.rb:243:in `block in configure'
2020-04-02 14:26:58 +0000 [error]: config error file="/fluentd/etc/fluentd.conf" error_class=Fluent::ConfigError error="start_namespace_watch: Exception encountered setting up namespace watch from Kubernetes API v1 endpoint https://10.96.0.1:443: namespaces is forbidden: User \"system:serviceaccount:deis:deis-logger-fluentd\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope ({\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"namespaces is forbidden: User \\\"system:serviceaccount:deis:deis-logger-fluentd\\\" cannot list resource \\\"namespaces\\\" in API group \\\"\\\" at the cluster scope\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"namespaces\"},\"code\":403}\n)"


➜  k8s kd describe po deis-monitor-telegraf-d9xqc
Events:
  Type     Reason   Age                    From          Message
  ----     ------   ----                   ----          -------
  Warning  BackOff  4m51s (x292 over 69m)  kubelet, m01  Back-off restarting failed container

```

**Comment by bacongobbler** [comment] 2020-04-02 14:54
> I can't say if there's a good explanation for this. @bacongobbler ?

The error you are seeing seems related to https://github.com/helm/helm/issues/7812, @kingdonb. Kubernetes broke backward compatibility somewhere around 1.14/1.15, which in turn broke `helm status`. In order to fix that, we had to change some bits around how we generate internal kubernetes objects, which likely caused this error to crop up. I'd follow up there and see if you can find out anything more on what causes this (or if you can identify a fix).

https://github.com/helm/helm/pull/7840 could potentially fix this issue, so I'd try that as well.

**Comment by ChillarAnand** [comment] 2020-04-02 15:15
Thanks, @bacongobbler 

That fix is on 2.16.x and we cant use 2.16.x to install workflow. I have upgraded to helm 3.1.2.

Do you know how to install workflow with it? This doesn't seem to work.

```
➜  k8s helm install hephy/workflow --namespace deis --set router.host_port.enabled=true --generate-name
Error: create: failed to create: namespaces "deis" not found
```

**Comment by bacongobbler** [comment] 2020-04-02 15:46
Run `kubectl create namespace deis`, or use the `--create-namespace` flag.

**Comment by ChillarAnand** [comment] 2020-04-02 16:08
Thanks, @bacongobbler 

With a new minikube k8s cluster and helm 3.1.2, it is still in same state. 

```
➜  k8s kd get po
NAME                                     READY   STATUS             RESTARTS   AGE
deis-builder-57cf7db484-x8rgw            0/1     Running            0          10m
deis-controller-7fbd88b5f8-ps86w         1/1     Running            4          10m
deis-database-66f68b9776-5tdk7           1/1     Running            0          10m
deis-logger-58bb65fdd7-sgdbm             1/1     Running            0          10m
deis-logger-fluentd-8gc7d                0/1     CrashLoopBackOff   6          10m
deis-logger-redis-5976d6ddc7-nt9pr       1/1     Running            0          10m
deis-minio-54f57f88b8-m7w9d              1/1     Running            0          10m
deis-monitor-grafana-6454b46bd8-w2v45    1/1     Running            0          10m
deis-monitor-influxdb-69f85d6d56-pttcd   1/1     Running            0          10m
deis-monitor-telegraf-h4hlx              0/1     CrashLoopBackOff   6          10m
deis-nsqd-6dc776449-ph75x                1/1     Running            0          10m
deis-registry-677fdfd6cf-xhnbg           1/1     Running            1          10m
deis-registry-proxy-x7b9w                1/1     Running            0          10m
deis-router-f9998457c-5blcr              0/1     CrashLoopBackOff   7          10m
deis-workflow-manager-5564f67d4-9z2tz    1/1     Running            0          10m
```

**Comment by kingdonb** [comment] 2020-04-02 16:51
Thanks @bacongobbler! That's super helpful. I will take a look at those, and follow up with my own testing to see if the issue can be resolved through that PR.

@ChillarAnand The error you're seeing now, using both Helm 2.15 and Helm 3.x, is a failure to enable rbac when your cluster has RBAC requirements enabled on it. When you run "helm install" or "helm upgrade --install" please try adding `--set global.use_rbac=true`, or otherwise find a way to set this in your helm chart values.

It probably makes sense to enable RBAC by default for Workflow in the next minor release, given we will be adding support for K8s 1.16+, I think it's probably true that by now, everyone and their uncles and aunts must have RBAC enabled by default on their clusters. I'm not sure if there are any tools like minikube at this point that don't enable RBAC by default, so we should follow suit.

**Comment by ChillarAnand** [comment] 2020-04-02 17:19
Thanks, @kingdonb 
I have created a new cluster and installed workflow with 
```
➜  k8s helm install hephy/workflow --namespace deis --set router.host_port.enabled=true --set global.use_rbac=true --generate-name 

➜  k8s kd get po
NAME                                     READY   STATUS             RESTARTS   AGE
deis-builder-57cf7db484-m6nk8            1/1     Running            2          8m56s
deis-controller-7fbd88b5f8-2mxhx         1/1     Running            3          8m56s
deis-database-66f68b9776-drxlv           1/1     Running            0          8m56s
deis-logger-58bb65fdd7-8rr8g             1/1     Running            4          8m56s
deis-logger-fluentd-8grzg                1/1     Running            0          8m56s
deis-logger-redis-5976d6ddc7-zmn7x       1/1     Running            0          8m56s
deis-minio-54f57f88b8-sz75w              1/1     Running            0          8m56s
deis-monitor-grafana-6454b46bd8-hjkbg    1/1     Running            0          8m56s
deis-monitor-influxdb-69f85d6d56-mvr6v   1/1     Running            0          8m56s
deis-monitor-telegraf-ngkcd              0/1     CrashLoopBackOff   6          8m56s
deis-nsqd-6dc776449-szfcz                1/1     Running            0          8m56s
deis-registry-677fdfd6cf-4m9ds           1/1     Running            0          8m55s
deis-registry-proxy-tqvrj                1/1     Running            0          8m56s
deis-router-f9998457c-q7vdb              1/1     Running            0          8m56s
deis-workflow-manager-5564f67d4-m5f9j    1/1     Running            0          8m56s
```

Only telegraf seems to be failing.
```
 ➜  k8s kd logs deis-monitor-telegraf-ngkcd

➜  k8s kd describe pod deis-monitor-telegraf-ngkcd
 Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  9m50s                   default-scheduler  Successfully assigned deis/deis-monitor-telegraf-ngkcd to m01
  Normal   Pulling    9m47s                   kubelet, m01       Pulling image "hephy/telegraf:v2.11.1"
  Normal   Pulled     9m20s                   kubelet, m01       Successfully pulled image "hephy/telegraf:v2.11.1"
  Warning  Failed     9m19s                   kubelet, m01       Error: failed to start container "deis-monitor-telegraf": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/run/utmp\\\" to rootfs \\\"/var/lib/docker/overlay2/8abb7fb589f34edb2b51e69c96571d67f1875b203b3f902138e799a7d760a4fe/merged\\\" at \\\"/var/lib/docker/overlay2/8abb7fb589f34edb2b51e69c96571d67f1875b203b3f902138e799a7d760a4fe/merged/run/utmp\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Warning  Failed     9m18s                   kubelet, m01       Error: failed to start container "deis-monitor-telegraf": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/run/utmp\\\" to rootfs \\\"/var/lib/docker/overlay2/fad0bddb48f64da2412b5f33df6008162f5deb16f0599f8185f14add402ee1cd/merged\\\" at \\\"/var/lib/docker/overlay2/fad0bddb48f64da2412b5f33df6008162f5deb16f0599f8185f14add402ee1cd/merged/run/utmp\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Warning  Failed     9m5s                    kubelet, m01       Error: failed to start container "deis-monitor-telegraf": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/run/utmp\\\" to rootfs \\\"/var/lib/docker/overlay2/fe5f770220eb9f91cebfa3431519d2d9c897c226ddc3ff37ab6a80d6e045af64/merged\\\" at \\\"/var/lib/docker/overlay2/fe5f770220eb9f91cebfa3431519d2d9c897c226ddc3ff37ab6a80d6e045af64/merged/run/utmp\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Warning  Failed     8m39s                   kubelet, m01       Error: failed to start container "deis-monitor-telegraf": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/run/utmp\\\" to rootfs \\\"/var/lib/docker/overlay2/7fb8f9ec70239bdfefbcbd319227d84ab26e3fe912a83e1a1ae8477386be3d95/merged\\\" at \\\"/var/lib/docker/overlay2/7fb8f9ec70239bdfefbcbd319227d84ab26e3fe912a83e1a1ae8477386be3d95/merged/run/utmp\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Normal   Pulled     7m47s (x4 over 9m19s)   kubelet, m01       Container image "hephy/telegraf:v2.11.1" already present on machine
  Normal   Created    7m46s (x5 over 9m19s)   kubelet, m01       Created container deis-monitor-telegraf
  Warning  Failed     7m46s                   kubelet, m01       Error: failed to start container "deis-monitor-telegraf": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/run/utmp\\\" to rootfs \\\"/var/lib/docker/overlay2/21795f591164fb6fff57b6a090a7ff9830019ee183b0d30f9dc50bafecd41c72/merged\\\" at \\\"/var/lib/docker/overlay2/21795f591164fb6fff57b6a090a7ff9830019ee183b0d30f9dc50bafecd41c72/merged/run/utmp\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Warning  BackOff    4m46s (x20 over 8m55s)  kubelet, m01       Back-off restarting failed container
```

**Comment by kingdonb** [comment] 2020-04-02 17:53
Thanks @ChillarAnand – can you give some details about your cluster and how it was provisioned? I feel like I have seen this one before but drawing a blank here.

Is it a managed cluster, if so what service provider managing; if not a managed service, then what process have you used to stand it up (kops, kubeadm, kind, k3s?)

I think the last time I saw this telegraf issue reported it was a `kind` user, trying to build a process for their CI system to create workflow deployments in an automated way. I'm not finding any notes about how they resolved the telegraf CrashLoopBackOff.

I wonder, if you are using kind (please confirm or deny) is it possible that /var/run/utmp does not exist on the machine that runs kind? That's what the error message in the log you posted seems to suggest, but I'm not sure what that means or why it would be a problem.

Sure seems clear, you can't mount a non-directory or non-existent path to a directory path in the container. (But why is /var/run/utmp being mounted, and what will be the other results of this failure? I can't answer these, don't know enough about monitor+logger+telegraf stack.)

It looks like telegraf is part of the deis-monitor stack that sits between nsq and influxdb, probably involved in collecting metrics, so while you have this failure, you may not be able to use at least `deis logs` feature, or possibly some data will be missing in grafana, but everything else should work.

```
mounting \\\"/var/run/utmp\\\" to rootfs \\\"/var/lib/docker/overlay2/.../merged\\\" at \\\"/var/lib/docker/overlay2/.../merged/run/utmp\\\" caused \\\"not a directory\\\
"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

This seems to be a common issue that is reported against a number of projects that are using telegraf, it looks like maybe we just need to make sure we upgrade to the latest telegraf in the next workflow release. I don't know, and it's not clear to me where this failure is coming from.

**Comment by ChillarAnand** [comment] 2020-04-02 17:58
I am testing this locally using minikube cluster. Starting cluster with 

```
$ minikube start --memory=8g
```

**Comment by kingdonb** [comment] 2020-04-02 18:38
We will try to repro on a minikube setup then, before our next release, to see if there's something we can do about telegraf. Thanks for persistence and making clear reports, this will be helpful for others who might trip over the same things between now and whenever we can make that release!

**Comment by ChillarAnand** [comment] 2020-04-07 15:04
On Mac minikube cluster, workflow is installing without any errors. 
On AWS ec2 (Ubuntu 18.04) minikube cluster, the above mentioned issue is happening. 

On AWS EKS cluster, installing workflow is stuck at the following step from ~30 minutes.

<img width="1235" alt="Screenshot 2020-04-07 at 7 39 10 PM" src="https://user-images.githubusercontent.com/4463796/78682768-0d6c6f00-790c-11ea-904e-cf2b4e93cd27.png">

After uninstalling workflow, without deleting the cluster using the following commands and then reinstalling worked. Not sure what might be the issue. 
```
➜  k8s k delete namespace deis

➜  k8s k delete clusterrole deis:deis-router deis:deis-workflow-manager deis:deis-controller deis:deis-logger-fluentd   deis:deis-router deis:deis-builder 
➜  k8s k delete clusterrolebinding deis:deis-router deis:deis-workflow-manager deis:deis-controller deis:deis-logger-fluentd   deis:deis-router deis:deis-builder 

```

**Comment by Cryptophobia** [comment] 2020-04-07 15:14
Hi @ChillarAnand , from the looks of it the registry proxy is not able to resolve the internal ip address of the registry pod, likely because it's not deployed as ClusterIP service.

When working with EKS or k8s on AWS it is best to configure the ECR registry instead of using the built in registry component anyways.

Here are some instructions for that: https://docs.teamhephy.com/installing-workflow/configuring-registry/

**Comment by ChillarAnand** [comment] 2020-04-08 01:47
Unable to update the registry as helm inspect seems to be failing. 

```
➜  k8s helm repo list
NAME            URL                                
hephy           https://charts.teamhephy.com/      
appscode        https://charts.appscode.com/stable/
➜  k8s helm ls --all 

NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
rabbitmq        default         1               2020-04-07 18:11:34.278973 +0530 IST    deployed        rabbitmq-ha-1.44.1      3.8.0      

➜  k8s helm inspect values helpy/workflow 
Error: failed to download "helpy/workflow" (hint: running `helm repo update` may help)

➜  k8s helm repo update                   
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "appscode" chart repository
...Successfully got an update from the "hephy" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

➜  k8s helm inspect values helpy/workflow 
Error: failed to download "helpy/workflow" (hint: running `helm repo update` may help)
```

**Comment by ChillarAnand** [comment] 2020-04-08 08:42
Is still kops is the recommended way to install hephy on AWS? Now, there is eksctl which will spin up the cluster with just 1 command.

**Comment by Cryptophobia** [comment] 2020-04-27 19:29
I am closing this as we figured out the issue and you were able to install. Please open another issue if having other problems.

**Closed by Cryptophobia** 2020-04-27 19:29 UTC
